export const DEFAULT_PIPELINE_NAME = 'Asosiy savdo';

export const DEFAULT_STAGES = [
  { id: 'NEW', label: 'Yangi' },
  { id: 'CONTACTED', label: 'Gaplashilgan' },
  { id: 'IN_PROGRESS', label: 'Jarayonda' },
  { id: 'FOLLOW_UP', label: 'Qayta aloqaga chiqish' },
  { id: 'FUTURE_SALE', label: 'Keyinchalik sotuv' },
  { id: 'DEPOSIT_RECEIVED', label: 'Zaklad olingan' },
  { id: 'PAID', label: "To'lov qilindi" },
  { id: 'INSTALLATION_REQUIRED', label: "O'rnatish kerak" },
  { id: 'INSTALLED', label: "O'rnatib bo'ldi" },
];

export const ALL_PERMISSIONS = [
  'dashboard.view',
  'customers.view',
  'customers.create',
  'customers.edit',
  'customers.delete',
  'customers.viewAll',
  'customers.viewOwn',
  'customers.viewGroups',
  'customers.amount.view',
  'customers.deposit.view',
  'customers.phone.view',
  'customer-groups.view',
  'customer-groups.create',
  'customer-groups.edit',
  'businesses.view',
  'businesses.create',
  'businesses.edit',
  'leads.view',
  'leads.create',
  'leads.edit',
  'leads.assign',
  'leads.convert',
  'deals.view',
  'deals.create',
  'deals.edit',
  'deals.changeStage',
  'deals.assign',
  'quotations.view',
  'quotations.create',
  'quotations.edit',
  'quotations.send',
  'payments.view',
  'payments.create',
  'payments.edit',
  'tasks.view',
  'tasks.create',
  'tasks.edit',
  'tasks.assign',
  'tasks.viewAll',
  'activities.view',
  'activities.create',
  'activities.edit',
  'installations.view',
  'installations.create',
  'installations.edit',
  'installations.assign',
  'attachments.create',
  'comments.create',
  'comments.view',
  'history.view',
  'reminders.view',
  'reminders.create',
  'employees.view',
  'employees.create',
  'employees.edit',
  'employees.delete',
  'teams.view',
  'teams.create',
  'teams.edit',
  'notifications.view',
  'notifications.manage',
  'reports.view',
  'profit.view',
  'settings.view',
  'settings.edit',
];

export const ROLE_DEFAULT_PERMISSIONS: Record<string, string[]> = {
  ADMIN: ALL_PERMISSIONS,
  SUPER_ADMIN: ALL_PERMISSIONS,
  MANAGER: ALL_PERMISSIONS.filter((p) => !p.startsWith('employees.delete')),
  SALES: [
    'dashboard.view',
    'customers.view',
    'customers.create',
    'customers.edit',
    'customer-groups.view',
    'customer-groups.create',
    'customer-groups.edit',
    'businesses.view',
    'businesses.create',
    'businesses.edit',
    'leads.view',
    'leads.create',
    'leads.edit',
    'leads.assign',
    'leads.convert',
    'deals.view',
    'deals.create',
    'deals.edit',
    'deals.changeStage',
    'quotations.view',
    'quotations.create',
    'quotations.edit',
    'quotations.send',
    'payments.view',
    'tasks.view',
    'activities.view',
    'activities.create',
    'attachments.create',
    'comments.create',
    'notifications.view',
  ],
  EMPLOYEE: ['dashboard.view', 'customers.view', 'tasks.view', 'activities.view', 'activities.create', 'notifications.view'],
  INSTALLER: ['dashboard.view', 'customers.view', 'installations.view', 'installations.edit', 'tasks.view', 'activities.view', 'activities.create'],
};
