export const DEFAULT_PIPELINE_NAME = 'Asosiy savdo';

export const DEFAULT_STAGES = [
  { id: 'NEW', label: 'Yangi', isSystem: true },
  { id: 'CONTACTED', label: 'Gaplashilgan', isSystem: true },
  { id: 'IN_PROGRESS', label: 'Jarayonda', isSystem: true },
  { id: 'FOLLOW_UP', label: 'Qayta aloqaga chiqish', isSystem: true },
  { id: 'FUTURE_SALE', label: 'Keyinchalik sotuv', isSystem: true },
  { id: 'DEPOSIT_RECEIVED', label: 'Zaklad olingan', isSystem: true },
  { id: 'PAID', label: "To'lov qilindi", isSystem: true },
  { id: 'INSTALLATION_REQUIRED', label: "O'rnatish kerak", isSystem: true },
  { id: 'INSTALLED', label: "O'rnatib bo'ldi", isFinal: true, isSystem: true },
];

export const ALL_PERMISSIONS = [
  'customers.view',
  'customers.viewAll',
  'customers.create',
  'customers.edit',
  'customers.editCore',
  'customers.viewCreatedBy',
  'customers.delete',
  'customers.viewPhone',
  'customers.viewAmount',
  'customers.viewDeposit',
  'customers.viewPipelineTotal',
  'customers.viewFinancials',
  'calls.view',
  'calls.create',
  'reminders.view',
  'reminders.viewAll',
  'reminders.create',
  'reminders.edit',
  'employees.view',
  'employees.create',
  'employees.edit',
  'employees.delete',
  'tasks.view',
  'tasks.viewAll',
  'tasks.create',
  'tasks.edit',
  'tasks.delete',
  'comments.view',
  'comments.create',
  'activities.view',
  'activities.create',
  'history.view',
  'programs.view',
  'programs.create',
  'programs.edit',
  'programs.delete',
  'teams.view',
  'teams.create',
  'teams.edit',
  'teams.delete',
  'businesses.view',
  'businesses.create',
  'businesses.edit',
  'leads.view',
  'leads.create',
  'leads.edit',
  'leads.delete',
  'leads.convert',
  'deals.view',
  'deals.create',
  'deals.edit',
  'deals.changeStage',
  'quotations.view',
  'quotations.create',
  'quotations.edit',
  'payments.view',
  'payments.create',
  'installations.view',
  'installations.viewAll',
  'installations.create',
  'installations.edit',
  'attachments.create',
  'dashboard.view',
  'profit.view',
  'settings.view',
  'settings.edit',
  'settings.create',
  'settings.delete',
];

export const ROLE_DEFAULT_PERMISSIONS: Record<string, string[]> = {
  ADMIN: ALL_PERMISSIONS,
  SUPER_ADMIN: ALL_PERMISSIONS,
  EMPLOYEE: [
    'customers.view',
    'customers.create',
    'customers.edit',
    'customers.viewPhone',
    'customers.viewAmount',
    'customers.viewDeposit',
    'customers.viewPipelineTotal',
    'customers.viewFinancials',
    'calls.view',
    'calls.create',
    'reminders.view',
    'reminders.create',
    'tasks.view',
    'tasks.create',
    'comments.view',
    'comments.create',
    'activities.view',
    'activities.create',
    'history.view',
    'programs.view',
  ],
  MANAGER: ALL_PERMISSIONS,
  SALES: ['customers.view', 'customers.create', 'customers.edit', 'tasks.view', 'programs.view'],
  SUPPORT: ['customers.view', 'tasks.view'],
  INSTALLER: ['customers.view', 'tasks.view'],
  DEVELOPER: ['customers.view', 'tasks.view', 'programs.view', 'settings.view'],
  PARTNER: ['customers.view'],
};
